### ISSUE TITLE
Where can  I find your supplementary materials？

### ISSUE THREAD

**Issue by feifeitu1** [qrzou/ParCo#1]
Very awesome idea！I am very interested about your body partition. Where can  I find your supplementary materials？Thank you for your reply very much!!!

**Comment by qrzou** [comment]
Hi, thank you for your interest. we will update it in the future.

**Comment by qrzou** [comment]
Hi, we have updated our paper on arxiv with supplementary, you can find the partition details in the supplementary.

**Comment by feifeitu1** [comment]
Ok，Thank you！
