### ISSUE TITLE
Hyparameters for HumanML3D

### ISSUE THREAD

**Issue by Githubhgh** [qrzou/ParCo#2]
Hi there,

Thanks for sharing the code, actually I found that the repository only contains the KIT training details, would you mind sharing the HumanML3D setting?

**Comment by qrzou** [comment]
Hi, 
The training commands listed in [3. Train ParCo](https://github.com/qrzou/ParCo?tab=readme-ov-file#3-train-parco) are the configuration for HumanML3D.
If you need to train on KIT-ML, just change '--dataname t2m'  to '--dataname kit'.

**Comment by Githubhgh** [comment]
Thank you for your response. Just to confirm, the KIT-ML and HumanML3D will use the same parameters, correct?

**Comment by qrzou** [comment]
If "parameters" you mentioned refers to training configuration, the answer is YES. They use nearly the same training configuration (except for `--dataname`)

**Comment by Githubhgh** [comment]
Thanks, I think it is clear now.
