### ISSUE TITLE
What gpu do you use when you train Parco_trans?

### ISSUE THREAD

**Issue by feifeitu1** [qrzou/ParCo#3]
Hello,can you tell me what gpu do you use when you train Parco_trans and how long it takes?When I train the second part using RTX3090 , I meet the question that cuda is out of memory.Thank you!

**Comment by qrzou** [comment]
We use A100-40GB to train ParCo, see `Computational resource consumption` in our readme for details.

**Comment by feifeitu1** [comment]
Oh，I see it now. Thank you for your reply!
