### ISSUE TITLE
Random seed fixed question

### ISSUE THREAD

**Issue by seoneun** [qrzou/ParCo#5]
Thank you for your great works!

I have one question.
As I run your code in this repository, I see that the performance was as good as described in the paper.

You used the code below to control the randomness.
'''
torch.manual_seed(args.seed)
'''
But I know that it is difficult to control randomness with this alone.
In reality, the performance was slightly different each time I trained.

So, I insert below code to control the randomness.
'''
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
'''
However, by doing this, the learning time slowed down by more than 100 times in vq training.

If you know the cause of this, I would appreciate it if you could explain.

Thank you!

**Comment by qrzou** [comment]
Your configuration of cudnn improves the certainty, but at the same time, it slows down the torch computation.

**Comment by seoneun** [comment]
So is it impossible to get exactly the same results every time I train?

**Comment by qrzou** [comment]
We haven't conducted experiments of it; you could try to achieve the same results.

**Comment by seoneun** [comment]
Thank you for your kind answer. :)
