### ISSUE TITLE
Evaluation code error

### ISSUE THREAD

**Issue by seoneun** [qrzou/ParCo#6]
Hello. Thank you for your work!

After training using your code, I keep getting "multimodality" as 0 when evaluating. Can you tell me why?

Thank you!

![image](https://github.com/user-attachments/assets/f006ba95-cc66-4076-82b8-ca1e493ac234)

**Comment by qrzou** [comment]
Hi, this is not error, please refer to 4.2. Part-Coordinated Transformer:

>  If you want to evaluate the MultiModality (which takes a long time), just delete --skip-mmod.

**Comment by seoneun** [comment]
Thank you so much!
