### ISSUE TITLE
Initialize the first state pose

### ISSUE THREAD

**Issue by bmhungqb** [qrzou/ParCo#8]
Hi, thanks for your great work. May I ask, can I initialize the first state pose to produce motion? How can I define the length of each parts (like in the image below, where I want to define L1, L, etc.)?
![image](https://github.com/user-attachments/assets/529dd134-7800-48a4-833d-9b1414a56347)

Thank you!

**Comment by qrzou** [comment]
Hi, thanks for your interest, you can refer to our whole-to-parts & parts-to-whole code to figure out how we conduct the partition and to support your own features:
https://github.com/qrzou/ParCo/blob/12c28f73bc874789e04bbe98399897ca8e8364b2/dataset/dataset_VQ_bodypart.py#L107
https://github.com/qrzou/ParCo/blob/12c28f73bc874789e04bbe98399897ca8e8364b2/dataset/dataset_VQ_bodypart.py#L223
