### ISSUE TITLE
how to get VQVAEV3_CB1024_CMT_H1024_NRES3

### ISSUE THREAD

**Issue by bmhungqb** [qrzou/ParCo#9]
Hi, thanks for the great work! I'm struggling with preparing extractors since I am using a different pose (15 points). I need to retrain [T2M](https://github.com/EricGuo5513/text-to-motion). The output looks like this:
![image](https://github.com/user-attachments/assets/0dce71ef-ca79-4880-9563-21964280d419)
How can I create the folder **VQVAEV3_CB1024_CMT_H1024_NRES3**, similar to the extractor that you provided?
Thank you.

**Comment by qrzou** [comment]
Hi, the implementation of this feature is directly inherited from the [T2M-GPT](https://mael-zys.github.io/T2M-GPT/) project (which likely builds upon the [T2M](https://github.com/EricGuo5513/text-to-motion) project's implementations), with no modifications made on our part. 

A practical approach might be to explore the original repositories of these projects to understand how they handle the processes, which could support the integration of the new features you require.

**Comment by bmhungqb** [comment]
> Hi, the implementation of this feature is directly inherited from the [T2M-GPT](https://mael-zys.github.io/T2M-GPT/) project (which likely builds upon the [T2M](https://github.com/EricGuo5513/text-to-motion) project's implementations), with no modifications made on our part.
> 
> A practical approach might be to explore the original repositories of these projects to understand how they handle the processes, which could support the integration of the new features you require.

Thank you
